export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const USER_SIGN_IN_FULFILLED = 'USER_SIGN_IN_FULFILLED';
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SIGNING_IN_REQUEST = 'SIGNING_IN_REQUEST';
