export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const USER_SIGN_UP_FULFILLED = 'USER_SIGN_UP_FULFILLED';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';
export const LOADING = 'LOADING';
