// Action types for all Articles
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_LOADING = "FETCH_ARTICLE_LOADING";
export const FETCH_ARTICLE_ERROR = "FETCH_ARTICLE_ERROR";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_LOADING = "FETCH_ARTICLES_LOADING";
export const FETCH_ARTICLES_ERROR = "FETCH_ARTICLES_ERROR";
