export const ARTICLE_SEARCH_FILTER_SUCCESS = "ARTICLE_SEARCH_FILTER_SUCCESS";
export const ARTICLE_SEARCH_FILTER_LOADING = "ARTICLE_SEARCH_FILTER_LOADING";
export const ARTICLE_SEARCH_FILTER_ERROR = "ARTICLE_SEARCH_FILTER_ERROR";
