export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const CREATE_ARTICLE_LOADING = 'CREATE_ARTICLE_LOADING';
