export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT_USER = "LOG_OUT_USER";
export const IS_LOADING = "IS_LOADING";
export const CREATE_ARTICLE_SUCCESSFUL = "CREATE_ARTICLE_SUCCESSFUL";
export const CREATE_ARTICLE_FAILED = "CREATE_ARTICLE_FAILED";
