export const CREATE_DRAFT = 'CREATE_DRAFT';
export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS';
export const CREATE_DRAFT_ERROR = 'CREATE_DRAFT_ERROR';
export const FETCH_DRAFTS = 'FETCH_DRAFTS';
export const FETCH_DRAFTS_SUCCESS = 'FETCH_DRAFTS_SUCCESS';
export const FETCH_DRAFTS_ERROR = 'FETCH_DRAFTS_ERROR';
