export const FETCH_FAVOURITE_ARTICLES_REQUEST = 'FETCH_FAVOURITE_ARTICLES_REQUEST';
export const FETCH_FAVOURITE_ARTICLES_SUCCESS = 'FETCH_FAVOURITE_ARTICLES_SUCCESS';
export const FETCH_FAVOURITE_ARTICLES_FAILED = 'FETCH_FAVOURITE_ARTICLES_FAILED';
