export const FETCH_PUBLISHED_ARTICLES_REQUEST = 'FETCH_PUBLISHED_ARTICLES_REQUEST';
export const FETCH_PUBLISHED_ARTICLES_SUCCESS = 'FETCH_PUBLISHED_ARTICLES_SUCCESS';
export const FETCH_PUBLISHED_ARTICLES_FAILED = 'FETCH_PUBLISHED_ARTICLES_FAILED';
