export const FETCH_READING_STATS_SUCCESS = 'FETCH_READING_STATS_SUCCESS';
export const FETCH_READING_STATS_REQUEST = 'FETCH_READING_STATS_REQUEST';
export const FETCH_READING_STATS_FAILED = 'FETCH_READING_STATS_FAILED';
