export const FETCH_RELATED_ARTICLE_LOADING = "FETCH_RELATED_ARTICLE_LOADING";
export const FETCH_RELATED_ARTICLE_SUCCESS = "FETCH_RELATED_ARTICLE_SUCCESS";
export const FETCH_RELATED_ARTICLE_ERROR = "FETCH_RELATED_ARTICLE_ERROR";
