export const SIGN_IN_SUCCESS = 'USER_SIGN_IN_FULFILLED';
export const SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";





