export const FETCH_USER_FOLLOW_REQUEST = 'FETCH_USER_FOLLOW_REQUEST';
export const FETCH_USER_FOLLOW_FAILED = 'FETCH_USER_FOLLOW_FAILED';
export const FETCH_USER_FOLLOW_SUCCESS = 'FETCH_USER_FOLLOW_SUCCESS';
